/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VHYhwdu4gHf
 */
import Link from "next/link";
import { FtIcon } from "../CommonComponent/navbar";

export default function Footer() {
  return (
    <footer className="bg-slate-100 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 ">
        <div className="flex  flex-row justify-between ">
          <div className="flex flex-row p-y ">
            <div >
            <div className="flex items-center space-x-4">
            <FtIcon className="h-16 w-16 text-white" color = 'black'/>
            <span className="font-bold text-lg  text-black" >Crypto</span>
            </div>
            
              <nav aria-label="Footer navigation">
                <ul className="space-y-4 text-sm font-medium text-gray-600">
                  <li>
                    <Link className="hover:text-gray-900" href="#">
                      News + Updates
                    </Link>
                  </li>
                  <li>
                    <Link className="hover:text-gray-900" href="#">
                      Research
                    </Link>
                  </li>
                  <li>
                    <Link className="hover:text-gray-900" href="#">
                      About
                    </Link>
                  </li>
                  <li>
                    <Link className="hover:text-gray-900" href="#">
                      Graduate Program
                    </Link>
                  </li>
                  <li>
                    <Link className="hover:text-gray-900" href="#">
                      People
                    </Link>
                  </li>
                  <li>
                    <Link className="hover:text-gray-900" href="#">
                      Events
                    </Link>
                  </li>
                  <li>
                    <Link className="hover:text-gray-900" href="#">
                      Videos
                    </Link>
                  </li>
                  <li>
                    <Link className="hover:text-gray-900" href="#">
                      Member Portal
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>

          </div>

          <div>
            <div className="flex py-2 justify-between  mb-6">
              <TwitterIcon className="h-6 w-6 text-gray-600 hover:text-gray-900" />
              <FacebookIcon className="h-6 w-6 text-gray-600 hover:text-gray-900" />
              <InstagramIcon className="h-6 w-6 text-gray-600 hover:text-gray-900" />
              <LinkedinIcon className="h-6 w-6 text-gray-600 hover:text-gray-900" />
              <RssIcon className="h-6 w-6 text-gray-600 hover:text-gray-900" />
            </div>
            <nav aria-label="Footer navigation">
              <ul className="space-y-4 text-sm font-medium text-gray-600">
                <li>
                  <Link className="hover:text-gray-900" href="#">
                    42 Tokyo
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-gray-900" href="#">
                    School of Architecture + Planning
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-gray-900" href="#">
                    Accessibility
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-gray-900" href="#">
                    Donate to the 42Crypto
                  </Link>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </footer>
  );
}



function FlagIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}


function TwitterIcon(props:any) {
  return (
    <Link href="https://x.com/42crypto_">
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
    </Link>
  )
}


function FacebookIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props :any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function LinkedinIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function RssIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 11a9 9 0 0 1 9 9" />
      <path d="M4 4a16 16 0 0 1 16 16" />
      <circle cx="5" cy="19" r="1" />
    </svg>
  )
}
