/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HpuSGFKcNjk
 */

import InitiativeCard from "./InitiativeCard"


export function InitiativeList() {
  return (
    <div className="grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-4 p-5">
<InitiativeCard image="./initiative-logo-test.svg" name="Zero-knowledge Proofs" description="Advancing the state of zero-knowledge proofs to enhance privacy and security in blockchain technologies." directorname="Alice Johnson" hashtag="#cryptography #privacy #blockchain +42 more"/>
<InitiativeCard image="./initiative-logo-test.svg" name="Decentralized Identity (DID)" description="Promoting the adoption and development of decentralized identity solutions across various blockchain platforms." directorname="Bob Smith" hashtag="#identity #decentralization #blockchain +35 more"/>

<InitiativeCard image="./initiative-logo-test.svg" name="Ethereum Node Expansion" description="Supporting the growth and decentralization of the Ethereum network through increased node participation." directorname="Carol Taylor" hashtag="#ethereum #node #blockchain +20 more"/>

<InitiativeCard image="./initiative-logo-test.svg" name="Internet Computer Protocol (ICP)" description="Accelerating the development and adoption of the Internet Computer to create a more decentralized and efficient web." directorname="David Lee" hashtag="#internetcomputer #web3 #decentralization +15 more"/>

<InitiativeCard image="./initiative-logo-test.svg" name="Bitcoin Innovation Hub" description="Fostering innovation and research in the Bitcoin ecosystem to enhance its utility and adoption worldwide." directorname="Eva Green" hashtag="#bitcoin #innovation #cryptocurrency +50 more"/>

<InitiativeCard image="./initiative-logo-test.svg" name="Smart Contract Research" description="Advancing the capabilities and security of smart contracts through rigorous research and development." directorname="Frank Moore" hashtag="#smartcontracts #blockchain #security +30 more"/>

<InitiativeCard image="./initiative-logo-test.svg" name="Blockchain Scalability Solutions" description="Exploring and developing solutions to address the scalability challenges faced by blockchain networks." directorname="Grace Chen" hashtag="#blockchain #scalability #technology +25 more"/>

<InitiativeCard image="./initiative-logo-test.svg" name="Crypto Asset Management" description="Improving the tools and strategies for effective management of crypto assets in diverse market conditions." directorname="Henry White" hashtag="#crypto #assetmanagement #finance +40 more"/>

<InitiativeCard image="./initiative-logo-test.svg" name="Decentralized Finance (DeFi) Innovations" description="Pioneering new financial products and services in the DeFi space to revolutionize traditional finance." directorname="Isla Fisher" hashtag="#defi #finance #innovation +45 more"/>

<InitiativeCard image="./initiative-logo-test.svg" name="NFT Market Development" description="Promoting the growth and sustainability of the NFT market through strategic partnerships and innovations." directorname="Jack Brown" hashtag="#nft #art #blockchain +33 more"/>

    </div>
  )
}
