/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kwIAXXkG6sX
 */
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"

export  function PublishList() {
  return (
    <div className="max-w-3xl mx-auto p-10 my-8">
      <div className="space-y-6">

      <PublishCard title="Decentralized Identity: The Future of Online Verification"
             description="Yamamoto, K., Chen, L., Smith, J. et al. Decentralized Identity: The Future of Online Verification. Blockchain Rev Tech (2024)."
           link="https://doi.org/10.1038/s44222-024-00201-5"
          />

          <PublishCard title="Zero-Knowledge Proofs: Enhancing Privacy in Blockchain"
            description="Wang, F., Johnson, D., Estevez, R. et al. Zero-Knowledge Proofs: Enhancing Privacy in Blockchain. J Cryptogr Blockchain Technol (2024)."
            link="https://doi.org/10.1038/s44222-024-00301-3"
          />

          <PublishCard title="Blockchain in Supply Chain Management: A Comprehensive Analysis"
            description="Gupta, S., Lee, H., Sharma, P. et al. Blockchain in Supply Chain Management: A Comprehensive Analysis. Int J Blockchain Econ (2024)."
            link="https://doi.org/10.1038/s44222-024-00401-1"
          />

          <PublishCard title="Smart Contracts and Decentralized Applications: Driving Business Innovation"
            description="Martinez, R., Zhang, Y., Gupta, A. et al. Smart Contracts and Decentralized Applications: Driving Business Innovation. Blockchain Bus Rev (2024)."
            link="https://doi.org/10.1038/s44222-024-00501-z"
          />

          <PublishCard title="Tokenization of Assets on Blockchain: Opportunities and Challenges"
            description="O'Neil, C., Kurosawa, T., Nkosi, M. et al. Tokenization of Assets on Blockchain: Opportunities and Challenges. FinTech Blockchain Rev (2024)."
            link="https://doi.org/10.1038/s44222-024-00601-x"
          />

      </div>
    </div>
  )
}

export function PublishCard (props:any) {
  return (
        <div className="flex flex-col space-y-2">
          <Link href={`${props.link}`} className="text-xl hover:text-blue-500 font-semibold">{props.title}</Link>
          <p className="text-sm text-gray-600">
         {props.description} 
         </p>
         <Link className="text-sm hover:text-blue-500 text-gray-600" href={props.link} >{props.link}</Link>
          <div className="flex space-x-2">
            <Badge variant="secondary">#robotics</Badge>
            <Badge variant="secondary">#bioengineering</Badge>
            <Badge variant="secondary">#neurobiology</Badge>
            <Badge>+5 more</Badge>
          </div>
        </div>
  )
}

export default PublishList


